version: '3.8'

services:
  dataviz-playground:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL for collaboration features
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dataviz
      POSTGRES_USER: dataviz_user
      POSTGRES_PASSWORD: dataviz_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - collaboration

  # Optional: Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - collaboration

volumes:
  postgres_data:
  redis_data:
